// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.app_version,
  serverUrl: '/api',
  envName: 'PROD',
};
